### ISSUE TITLE
High Scores Control don't show anything

### ISSUE THREAD

**Issue by dne12** [danderle/WPF_Snake#1]
When using Snoop I get this error:

```
           Count   Data Context    Target                       Target Type         Description
Error       4       null            ExportOptions.TreeItem       TreeItem	     Cannot find governing FrameworkElement or FrameworkContentElement for target element.			
		
			
```

**Comment by danderle** [comment]
What do you mean by "Snoop" ?

**Comment by danderle** [comment]
What do you mean by "Snoop"?

**Comment by danderle** [comment]
I have made some changes, can you please check if the high scores a still not showing?

**Comment by danderle** [comment]
I have made some changes, can you please check if the high scores a now visible?

**Comment by dne12** [comment]
now it works again, thanks for the help.

snoop er et værktøy for og failsøke i wpf:
https://github.com/snoopwpf/snoopwpf
